#!/bin/bash

export MINIMAX_API_KEY=YOUR_MINIMAX_API_KEY
export MINIMAX_API_HOST="https://api.minimax.io"
export OPENROUTER_API_KEY=YOUR_OPENROUTER_API_KEY
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
